<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-27T15:35:34 IST" name="Suite" finished-at="2023-03-27T15:36:02 IST" duration-ms="28241">
    <groups>
    </groups>
    <test started-at="2023-03-27T15:35:34 IST" name="Test" finished-at="2023-03-27T15:36:02 IST" duration-ms="28241">
      <class name="Test.scenario_01_Test">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:34 IST" name="initDriver" finished-at="2023-03-27T15:35:38 IST" duration-ms="4212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validate_Entered_Message()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:39 IST" name="validate_Entered_Message" finished-at="2023-03-27T15:35:40 IST" duration-ms="1507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Entered_Message -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:40 IST" name="closeDriver" finished-at="2023-03-27T15:35:40 IST" duration-ms="274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:40 IST" name="initDriver" finished-at="2023-03-27T15:35:43 IST" duration-ms="2226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validate_Simple_Form_Demo_URL()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:43 IST" name="validate_Simple_Form_Demo_URL" finished-at="2023-03-27T15:35:43 IST" duration-ms="581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Simple_Form_Demo_URL -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.scenario_01_Test@6e9a5ed8]" started-at="2023-03-27T15:35:43 IST" name="closeDriver" finished-at="2023-03-27T15:35:43 IST" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Test.scenario_01_Test -->
      <class name="Test.scenario_03_Test">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:43 IST" name="initDriver" finished-at="2023-03-27T15:35:46 IST" duration-ms="2316" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validate_Error_Message()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:46 IST" name="validate_Error_Message" finished-at="2023-03-27T15:35:47 IST" duration-ms="992" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [KDGPlease fill out this field.] but found [Please fill out this field.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [KDGPlease fill out this field.] but found [Please fill out this field.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.scenario_03_Test.validate_Error_Message(scenario_03_Test.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Error_Message -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:47 IST" name="closeDriver" finished-at="2023-03-27T15:35:47 IST" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:47 IST" name="initDriver" finished-at="2023-03-27T15:35:50 IST" duration-ms="2317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validate_Success_Message()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:50 IST" name="validate_Success_Message" finished-at="2023-03-27T15:35:55 IST" duration-ms="5201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Success_Message -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.scenario_03_Test@45d84a20]" started-at="2023-03-27T15:35:55 IST" name="closeDriver" finished-at="2023-03-27T15:35:55 IST" duration-ms="427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Test.scenario_03_Test -->
      <class name="Test.scenario_02_Test">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:Test.scenario_02_Test@52f27fbd]" started-at="2023-03-27T15:35:55 IST" name="initDriver" finished-at="2023-03-27T15:35:58 IST" duration-ms="2419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validate_Dragged_Value()[pri:0, instance:Test.scenario_02_Test@52f27fbd]" started-at="2023-03-27T15:35:58 IST" name="validate_Dragged_Value" finished-at="2023-03-27T15:36:02 IST" duration-ms="4375" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [59] but found [95]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [59] but found [95]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.scenario_02_Test.validate_Dragged_Value(scenario_02_Test.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_Dragged_Value -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.scenario_02_Test@52f27fbd]" started-at="2023-03-27T15:36:02 IST" name="closeDriver" finished-at="2023-03-27T15:36:02 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Test.scenario_02_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
